openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: weather
      tags:
        - Weather endpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  coord:
                    type: object
                    description: ''
                    properties:
                      lon:
                        type: number
                        description: 'City geo location, longitude'
                      lat:
                        type: number
                        description: 'City geo location, latitude'
                  cod:
                    type: number
                    description: internal parameter
                  name:
                    type: string
                    description: Name
                  id:
                    type: number
                    description: City ID
                  timezone:
                    type: number
                    description: The timezone for the station
                  sys:
                    type: object
                    properties:
                      type:
                        type: number
                        description: internal parameter
                      id:
                        type: number
                        description: internal parameter
                      country:
                        type: string
                        description: 'Country code (US, JP)'
                      sunrise:
                        type: number
                        description: 'Sunrise time, UTC'
                      sunset:
                        type: number
                        description: 'Sunset time, UTC'
                  dt:
                    type: number
                    description: internal parameter
                  clouds:
                    type: object
                    properties:
                      all:
                        type: number
                        description: internal parameter
                  wind:
                    type: object
                    properties:
                      speed:
                        type: number
                        description: 'wind speed, in miles'
                      deg:
                        type: number
                        description: 'Wind temperature, in degrees'
                  visibility:
                    type: number
                    description: 'distance for visibility, in miles'
                  main:
                    type: object
                    properties:
                      temp:
                        type: number
                        description: 'temperature, in F '
                      feels_like:
                        type: number
                        description: 'What the temperature feels like, in F'
                      temp_min:
                        type: number
                        description: 'Maximum temperature of the day, in F'
                      temp_max:
                        type: number
                        description: 'Minimum temperature of the day, in F'
                      pressure:
                        type: number
                        description: Pressure in unit
                      humidity:
                        type: number
                        description: 'Humidity, in percent'
                  base:
                    type: string
                  weather:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: internal parameter
                        main:
                          type: string
                          description: internal parameter
                        description:
                          type: string
                          description: internal parameter
                        icon:
                          type: string
                          description: internal parameter
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_response'
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
            text/html:
              schema:
                type: object
                properties: {}
            text/plain:
              schema:
                type: object
                properties: {}
            application/EDI-X12:
              schema:
                type: object
                properties: {}
            application/EDIFACT:
              schema:
                type: object
                properties: {}
            application/atom+xml:
              schema:
                type: object
                properties: {}
            application/font-woff:
              schema:
                type: object
                properties: {}
            application/gzip:
              schema:
                type: object
                properties: {}
            application/javascript:
              schema:
                type: object
                properties: {}
          description: ''
          headers: {}
      operationId: get-weather
      security:
        - app_id: []
      description: Weather endpoints
      parameters:
        - schema:
            type: string
          in: query
          name: Zip
          description: '**Zip Code** Search by Zip Code. '
        - schema:
            type: string
          in: query
          name: lon
          description: '**Longitude**'
        - schema:
            type: string
          in: query
          name: lang
          description: '**Language**'
        - schema:
            type: string
          in: query
          name: lat
          description: '**Latitude**'
components:
  schemas:
    unauthorized_response:
      title: 401
      type: object
      description: ''
      properties:
        cod:
          type: number
        '':
          type: string
      required:
        - cod
        - ''
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
